@startuml laba4
!define RECTANGLE(x) <b>x</b>

rectangle "Покупка авиабилетов" as A0 {
    RECTANGLE(Поиск рейсов) as A1
    RECTANGLE(Выбор рейса) as A2
    RECTANGLE(Оплата билетов) as A3
}

A1 --> A2 : Результаты поиска
A2 --> A3 : Выбранный рейс
A3 --> A0 : Подтверждение покупки

A0 <-down-> "Запрос на поиск" : Вход
A0 <-up-> "Управление" : Условия
A0 <-down-> "Система" : Механизмы
@enduml
