@startuml labaa4
title Диаграмма IDEF0: Система онлайн-покупки авиабилетов

package "Система онлайн-покупки" {
    [Клиент] --> [Система поиска] : Запрос на поиск рейсов
    [Система поиска] --> [Информация о рейсах] : Получение данных
    [Информация о рейсах] --> [Выбор рейса] : Отображение информации
    [Выбор рейса] --> [Система оплаты] : Запрос на оплату
    [Система оплаты] --> [Получение билетов] : Подтверждение оплаты
    [Получение билетов] --> [Авиакомпания] : Передача данных о покупке
}
@enduml
