@startuml laba2
|Клиент|
start
:Найти рейс;
|Система_поиска|
:Получить список рейсов;
|База_данных_авиарейсов|
:Список рейсов;
|Система_поиска|
:Список рейсов;
:Выбрать рейс;
:Получить информацию о рейсе;
|База_данных_авиарейсов|
:Информация о рейсе;
|Система_поиска|
:Информация о рейсе;
:Заказать билеты;
:Ввести данные о пассажирах;
|Клиент|
:Данные о пассажирах;
|Система_оплаты|
:Обработать платеж;
:Статус платежа;
|Система_поиска|
:Сохранить заказ;
|База_данных_авиарейсов|
:Номер заказа;
|Система_поиска|
:Номер заказа и электронный билет;
|Клиент|
:Получить подтверждение заказа;
|Авиакомпания|
:Подтверждение заказа;
stop
@enduml
