@startuml laba2
participant Клиент
participant Система_поиска
participant Система_оплаты
participant База_данных_авиарейсов
participant Авиакомпания
activate Клиент
Клиент -> Система_поиска: Найти рейс
activate Система_поиска
Система_поиска -> База_данных_авиарейсов: Получить список рейсов
activate База_данных_авиарейсов
База_данных_авиарейсов --> Система_поиска: Список рейсов
deactivate База_данных_авиарейсов
Система_поиска --> Клиент: Список рейсов
deactivate Система_поиска
Клиент -> Система_поиска: Выбрать рейс
activate Система_поиска
Система_поиска -> База_данных_авиарейсов: Получить информацию о рейсе
activate База_данных_авиарейсов
База_данных_авиарейсов --> Система_поиска: Информация о рейсе
deactivate База_данных_авиарейсов
Система_поиска --> Клиент: Информация о рейсе
deactivate Система_поиска
Клиент -> Система_поиска: Заказать билеты
activate Система_поиска
Система_поиска -> Клиент: Ввести данные о пассажирах
activate Клиент
Клиент --> Система_поиска: Данные о пассажирах
deactivate Клиент
Система_поиска -> Система_оплаты: Обработать платеж
activate Система_оплаты
Система_оплаты --> Система_поиска: Статус платежа
deactivate Система_оплаты
Система_поиска --> База_данных_авиарейсов: Сохранить заказ
activate База_данных_авиарейсов
База_данных_авиарейсов --> Система_поиска: Номер заказа
deactivate База_данных_авиарейсов
Система_поиска --> Клиент: Номер заказа и электронный билет
deactivate Система_поиска
Клиент -> Авиакомпания: Получить подтверждение заказа
activate Авиакомпания
Авиакомпания --> Клиент: Подтверждение заказа
deactivate Авиакомпания
deactivate Клиент
@enduml

