@startuml laba2
participant Клиент
participant Система_поиска
participant База_данных_авиарейсов
activate Клиент
Клиент -> Система_поиска: Запросить информацию о багаже
activate Система_поиска
Система_поиска -> База_данных_авиарейсов: Получить информацию о багаже
activate База_данных_авиарейсов
База_данных_авиарейсов --> Система_поиска: Информация о багаже
deactivate База_данных_авиарейсов
Система_поиска --> Клиент: Информация о багаже
deactivate Система_поиска
deactivate Клиент
@enduml
