@startuml laba2
|Клиент|
start
:Запросить информацию о багаже;
|Система_поиска|
:Получить информацию о багаже;
|База_данных_авиарейсов|
:Информация о багаже;
|Система_поиска|
:Информация о багаже;
|Клиент|
:Получить информацию о багаже;
stop
@enduml
