@startuml laba3

class Сотрудник {
  отвечать_на_звонки()
  предоставлять_информацию_о_ценах()
  оформлять_заказ(Клиент, Заказ)
}

class Клиент {
  информация_о_клиенте
}

class Заказ {
  информация_о_заказе
}

class БазаДанныхКлиентов {
  хранить_информацию_о_клиентах()
  добавлять_нового_клиента(Клиент)
  находить_клиента(Клиент)
}

class БазаДанныхЗаказов {
  хранить_информацию_о_заказах()
  записывать_новый_заказ(Заказ)
  читать_существующие_заказы()
}

Сотрудник "1" -- "0..*" Клиент : взаимодействует
Сотрудник "1" -- "0..*" Заказ : формирует
Сотрудник "1" -- "1" БазаДанныхКлиентов : использует
Сотрудник "1" -- "1" БазаДанныхЗаказов : использует
Клиент "1" -- "0..*" Заказ : делает
Клиент "1" -- "1" БазаДанныхКлиентов : хранится

@enduml
