@startuml f

class Студент {
  регистрироваться_в_системе()
  просматривать_расписание()
  просматривать_оценки()
}

class Преподаватель {
  регистрироваться_в_системе()
  выбирать_группу_и_студента()
  выставлять_оценки()
  просматривать_расписание()
}

class БазаДанных {
  хранить_данные_студентов()
  хранить_данные_преподавателей()
  хранить_расписание()
  хранить_оценки_студентов()
}

Студент "1" -- "1" БазаДанных : взаимодействует
Преподаватель "1" -- "1" БазаДанных : взаимодействует
Преподаватель "1" -- "0..*" Студент : выставляет_оценки
Студент "0..*" -- "1" Преподаватель : обучается_у

@enduml
